$LastCommit = (git log -p -1)
$Sha = $LastCommit[0].Substring(7,8)
$commitNumber = (git rev-list --all --count)
$DateUpdate = $LastCommit[2].Substring(8,18)
$VersionFile = [System.IO.File]::ReadAllLines([System.IO.Directory]::GetCurrentDirectory()+"\Version.cs")
$VersionFile[6] = $VersionFile[6].Remove(41,3).Insert(41,$commitNumber)
$VersionFile[7] = $VersionFile[7].Remove(44,8).Insert(44,$Sha)
$VersionFile[8] = $VersionFile[8].Remove(80,18).Insert(80,$DateUpdate)
[System.IO.File]::WriteAllLines([System.IO.Directory]::GetCurrentDirectory()+"\Version.cs",$VersionFile)